apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
      app: api-gateway-app
  ports:
    - protocol: 'TCP'
      port: 8080
      targetPort: 8080
  type: ClusterIP